### ISSUE TITLE
FAQ: Adiabatic flame temperature

### ISSUE THREAD

**Issue by BernardoAMDAlmeida** [AlbertoCuadra/combustion_toolbox#906]
Where can I find the code for adiabatic flame temperature calculation?

**Comment by AlbertoCuadra** [comment]
Hello Bernardo,

This can be obtained using the desktop environment or with the GUI.

- Desktop environment: check https://combustion-toolbox-website.readthedocs.io/en/latest/examples/examples_plain_HP.html
- GUI: This website section is still under development but is quite simple. We can have a quick online meeting, e.g., via Google meet if you are available. I will update the tutorial content for the GUI as soon as possible.

Best,
Alberto

**Comment by BernardoAMDAlmeida** [comment]
Hello Alberto.
But where can I find the code behind the calculation with all the steps?
I take the opportunity to ask another thing. I wanted to have N2 as both fuel component and oxidizer, is it possible?

Best regards,
Bernardo

**Comment by AlbertoCuadra** [comment]
Hi Bernardo,

I see, the top layer for the chemical equilibrium calculations (CT-EQUIL module) corresponds with the function [equilibrate.m](https://github.com/AlbertoCuadra/combustion_toolbox/blob/master/modules/ct_equil/equilibrate.m), which  computes the chemical equilibrium composition and thermodynamic properties for any of the following pairs of state functions: TP, HP, SP, TV, EV, and SV, where T is temperature, P pressure, H enthalpy, S entropy, E internal energy, and V volume. The next layer is associated with the [equilibrate_T.m](https://github.com/AlbertoCuadra/combustion_toolbox/blob/master/modules/ct_equil/equilibrate_T.m) routine, which solves the chemical equilibrium problem for a fixed temperature and pressure/volume (Gibbs/Helmholtz), [equilibrate_gibbs.m](https://github.com/AlbertoCuadra/combustion_toolbox/blob/master/modules/ct_equil/equilibrium_gibbs.m) and [equilibrium_helmholtz.m](https://github.com/AlbertoCuadra/combustion_toolbox/blob/master/modules/ct_equil/equilibrium_helmholtz.m), respectively. The preprint of the Combustion Toolbox will be released in the next few weeks, and it will describe every part of the code.

Regarding your second question, yes, it's possible. For example:

```matlab
%% INITIALIZE
self = App('Soot formation');
%% INITIAL CONDITIONS
self = set_prop(self, 'TR', 300, 'pR', 1 * 1.01325, 'phi', 0.5:0.01:5);
self.PD.S_Fuel     = {'CH4', 'N2'};
self.PD.N_Fuel     = [0.8, 0.2];
self.PD.S_Oxidizer = {'N2', 'O2', 'Ar', 'CO2'};
self.PD.ratio_oxidizers_O2 = [78.084, 20.9476, 0.9365, 0.0319] ./ 20.9476;
%% ADDITIONAL INPUTS (DEPENDS OF THE PROBLEM SELECTED)
self = set_prop(self, 'pP', self.PD.pR.value); 
%% SOLVE PROBLEM
self = solve_problem(self, 'HP');
%% DISPLAY RESULTS (PLOTS)
post_results(self);
```

I hope this helps.

Best,
Alberto

**Comment by BernardoAMDAlmeida** [comment]
But even in ct_equil module, it does not show how the calculation is done, it will just be available in the next few weeks, right?

Understood. But in the toolbox it does not allow to have N2 as an oxidizer and fuel.
If I admit that N2 is just the oxidizer and enter the number of moles corresponding to both oxidizer and fuel, it is ok?

**Comment by AlbertoCuadra** [comment]
For problems where the temperature is not specified, Combustion Toolbox obtains the temperature at equilibrium by using a root finding method (see [root finding](https://github.com/AlbertoCuadra/combustion_toolbox/tree/master/utils/root_finding) folder). There are three root-finding algorithms implemented for this particular purpose, a Newton-Raphson (by default; second-order method), Newton-Steffensen (third-order method), and a Steffensen-Aitken (second-order method).

The code iterates until the state function of the problem selected remains unchanged (subject to a tolerance, by default 1e-3).
For example, for adiabatic combustion at constant pressure (HP), the enthalpy of the reactants and products is the same. So the code does the following:

1. Computes a guess of the temperature based on a regula falsi method or, in the case of parametric studies, using the temperature of the previous solution as an initial guess.
2. Iterate over the temperature using the root-finding method selected (by default [Newton-Raphson](https://github.com/AlbertoCuadra/combustion_toolbox/tree/master/utils/root_finding/newton)) until satisfying a certain tolerance (by default 1e-3).
   2.1. Solves the chemical equilibrium for a given temperature and pressure/volume using [equilibrium_gibbs.m](https://github.com/AlbertoCuadra/combustion_toolbox/blob/master/modules/ct_equil/equilibrium_gibbs.m) or [equilibrium_helmholtz.m](https://github.com/AlbertoCuadra/combustion_toolbox/blob/master/modules/ct_equil/equilibrium_helmholtz.m), respectively.
3. Computes the properties of the mixture.

---
You are right, that is not possible at the moment using the GUI. However, your workaround will work. I will open an issue and fixed as soon as possible. 

Best,
Alberto

**Comment by BernardoAMDAlmeida** [comment]
Hi Alberto!
Thank you for your help. Can I calculate the adiabatic flame temperature for non-chemical equilibrium reaction?

**Comment by AlbertoCuadra** [comment]
Hi Bernardo,

No, that is not possible at the moment. 

Best,
Alberto
